### ISSUE TITLE
Test scenarios for Datasource authentication

### ISSUE THREAD

**Issue by chandrams** [kruize/autotune#1286]
## Bearer Authentication Scenarios

- [x] Datasource authentication & connection with valid bearer token
	- [x] Valid token for bearer authentication
	
- [x] End-to-End test - pass valid bearer token & ensure recommendations are generated

- [x] Exception handling when incorrect token is passed
	- [x] Bearer authentication
		- [x] Expired token
		- [x] Invalid token
		- [x] Empty token
		- [ ] Invalid characters in token
			
- [ ] Authentication of Multiple datasources (Is it supported?)
- [x] Test with supported datasources	
- [x] Test logging for any authentication messages, retries
- [x] Validate documentation

**Comment by khansaad** [comment]
Updated the above list after the 1307 merge.

**Comment by khansaad** [comment]
The above issue has been updated to include only bearer auth scenarios and the basic auth scenarios has been moved to #1425 . 
Closing this issue since the bearer auth tests was added as part of #1307
