### ISSUE TITLE
Kruize Code base Clean up and structuring

### ISSUE THREAD

**Issue by bharathappali** [kruize/autotune#660]
This issue tracks the work which needs to be done as part of the kruize code base cleanup
- [x] Analyser
     - [x] Code clean up - [Done](https://github.com/kruize/autotune/pull/659)
     - [x] Code Structuring - [Done](https://github.com/kruize/autotune/pull/659)
- [ ] Experiment Manager
     - [ ] Code clean up
     - [ ] Code structuring

**Comment by bharathappali** [comment]
No longer a priority. Will reopen it if needed
